### ISSUE TITLE
TypeError: TextInputSequence must be str

### ISSUE THREAD

**Issue by Jutakajo** [forest-snow/alps#2]
I'm trying to run the code but I'm getting the following error:

 File "/Users/env/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py", line 385, in _batch_encode_plus
    encodings = self._tokenizer.encode_batch(

I am trying to run it on CPU.

Is there a known solution to this?

**Comment by forest-snow** [comment]
@Jutakajo this code was written with Transformers 2.8.0 where fast tokenizers were not available yet (?). I don't think you can directly use fast tokenizers with my code.

**Comment by Jutakajo** [comment]
thank you for your response, I couldn't pip install tokenizers and
transformers from requirements.txt as there was a dependency issue. I've
solved it with getting the following versions tokenizers==0.5.2
transformers==2.5.1 if anyone else has the same issue.

Regards,
Juta
