### ISSUE TITLE
other models

### ISSUE THREAD

**Issue by Jutakajo** [forest-snow/alps#3]
Hi, I was wondering if ALPS code works on any other model besides bert-uncased? I have tried bert-large-uncased, however, it stops after evaluation, just before starting to train without a message. Other models with MLM head like RoBERTa or DistillBERT gives another error,

  File "/home/jupyter/alps/src/sample.py", line 168, in get_scores_or_vectors
    assert check_model_head(model, args.sampling), "Model-sampling mismatch"
  File "/home/jupyter/alps/src/sample.py", line 37, in check_model_head
    raise NotImplementedError

**Comment by forest-snow** [comment]
Thanks for your message @Jutakajo

**Comment by forest-snow** [comment]
Thank you for your message @Jutakajo 

Our paper only ran experiments on bert-base-uncased and scibert_scivocab_uncased, so our code currently only supports these two models. I think the code can be extended to other models in huggingface but data preprocessing and model training will need to be modified.
